In [92]:
import numpy as pd 
import pandas as pd

In [93]:
movies = pd.read_csv('tmdb_5000_movies.csv')
credits = pd.read_csv('tmdb_5000_credits.csv')

In [94]:
movies.sample()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
190,130000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 16, ""...",http://www.us.movie.tintin.com/,17578,"[{""id"": 483, ""name"": ""riddle""}, {""id"": 1316, ""...",en,The Adventures of Tintin,"Intrepid young reporter, Tintin and his loyal ...",89.938296,"[{""name"": ""Paramount Pictures"", ""id"": 4}, {""na...","[{""iso_3166_1"": ""NZ"", ""name"": ""New Zealand""}, ...",2011-10-25,371940071,107.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"This year, discover how far adventure will tak...",The Adventures of Tintin,6.7,2061

In [95]:
movies.shape

(4803, 20)

In [96]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [97]:
credits.shape

(4803, 4)

In [98]:
# credits.head(1)['cast'].values

In [99]:
credits.columns

Index(['movie_id', 'title', 'cast', 'crew'], dtype='object')

In [100]:
# Merging on basics of title
movies = movies.merge(credits,on='title')

In [101]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [102]:
movies.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count', 'movie_id', 'cast', 'crew'],
      dtype='object')

### Extract the useful columns

* genres:-(Action,horror,love)
* keywords
* id
* title
* overview
* release_data
* revenue
* cast
* crew

In [103]:
movies = movies[['movie_id','title','overview','genres','keywords','cast','crew']]

In [104]:
movies.shape

(4809, 7)

In [105]:
movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [106]:
movies.dropna(inplace=True)

In [107]:
movies.duplicated().sum()

np.int64(0)

In [108]:
# convert string into list

In [109]:
movies.iloc[0].genres
# Here data is in the form of list of dic or string of list

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [110]:
# Extract the name from string of list
import ast 
def convert(obj): 
    l=[]
    for i in ast.literal_eval(obj):
        l.append(i['name'])
    return l

In [111]:
movies['genres']=movies['genres'].apply(convert)

In [112]:
movies.head(1)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [113]:
# import ast

# code = "a = 5 + 3"
# tree = ast.parse(code)

# print(ast.dump(tree))

In [114]:
print(type(movies['keywords'][0]))

<class 'str'>

In [115]:
movies['keywords']=movies['keywords'].apply(convert)

In [116]:
movies.head(1)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [117]:
# Now Extract the cast from string of list

In [118]:
# movies.cast[0]

In [119]:
# Extract first 5 character worked in the movies.

In [120]:
# Extract the name from string of list
import ast 
def convert3(obj): 
    l=[]
    counter=0
    for i in ast.literal_eval(obj):
        if counter !=3: 
            l.append(i['name'])
            counter+=1
        else: 
            break
    return l

In [121]:
movies['cast']=movies['cast'].apply(convert3)

In [122]:
# movies

In [123]:
# Now move on for crew(job roll in the movies like director,music composer etc)

In [124]:
# movies['crew'][0]

In [125]:
type(movies['cast'][0])

list

In [126]:
def fetch_director(obj): 
    l=[]
    for i in ast.literal_eval(obj): 
        if i['job']=='Director': 
            l.append(i['name'])
            break
    return l

In [127]:
movies['crew']=movies['crew'].apply(fetch_director)

In [128]:
print(type(movies['crew'][0]))

<class 'list'>

In [129]:
movies['overview'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [130]:
type(movies['overview'][0])

str

In [131]:
movies['overview']=movies['overview'].apply(lambda x:x.split())

In [132]:
type(movies['overview'][0])

list

In [133]:
# movies

In [134]:
# Removing space from the list because merging the sur_name of person.

In [135]:
movies['genres'].apply(lambda x:[i.replace(' ','') for i in x])

0       [Action, Adventure, Fantasy, ScienceFiction]
1                       [Adventure, Fantasy, Action]
2                         [Action, Adventure, Crime]
3                   [Action, Crime, Drama, Thriller]
4                [Action, Adventure, ScienceFiction]
                            ...
4804                       [Action, Crime, Thriller]
4805                               [Comedy, Romance]
4806               [Comedy, Drama, Romance, TVMovie]
4807                                              []
4808                                   [Documentary]
Name: genres, Length: 4806, dtype: object

In [136]:
movies['keywords'].apply(lambda x:[i.replace(' ','') for i in x])

0       [cultureclash, future, spacewar, spacecolony, ...
1       [ocean, drugabuse, exoticisland, eastindiatrad...
2       [spy, basedonnovel, secretagent, sequel, mi6, ...
3       [dccomics, crimefighter, terrorist, secretiden...
4       [basedonnovel, mars, medallion, spacetravel, p...
                              ...
4804    [unitedstates–mexicobarrier, legs, arms, paper...
4805                                                   []
4806    [date, loveatfirstsight, narration, investigat...
4807                                                   []
4808             [obsession, camcorder, crush, dreamgirl]
Name: keywords, Length: 4806, dtype: object

In [137]:
movies['overview'].apply(lambda x:[i.replace(' ','') for i in x])

0       [In, the, 22nd, century,, a, paraplegic, Marin...
1       [Captain, Barbossa,, long, believed, to, be, d...
2       [A, cryptic, message, from, Bond’s, past, send...
3       [Following, the, death, of, District, Attorney...
4       [John, Carter, is, a, war-weary,, former, mili...
                              ...
4804    [El, Mariachi, just, wants, to, play, his, gui...
4805    [A, newlywed, couple's, honeymoon, is, upended...
4806    ["Signed,, Sealed,, Delivered", introduces, a,...
4807    [When, ambitious, New, York, attorney, Sam, is...
4808    [Ever, since, the, second, grade, when, he, fi...
Name: overview, Length: 4806, dtype: object

In [138]:
movies['cast'].apply(lambda x:[i.replace(' ','') for i in x])

0        [SamWorthington, ZoeSaldana, SigourneyWeaver]
1           [JohnnyDepp, OrlandoBloom, KeiraKnightley]
2            [DanielCraig, ChristophWaltz, LéaSeydoux]
3            [ChristianBale, MichaelCaine, GaryOldman]
4          [TaylorKitsch, LynnCollins, SamanthaMorton]
                             ...
4804    [CarlosGallardo, JaimedeHoyos, PeterMarquardt]
4805         [EdwardBurns, KerryBishé, MarshaDietlein]
4806           [EricMabius, KristinBooth, CrystalLowe]
4807            [DanielHenney, ElizaCoupe, BillPaxton]
4808    [DrewBarrymore, BrianHerzlinger, CoreyFeldman]
Name: cast, Length: 4806, dtype: object

In [139]:
movies['crew'].apply(lambda x:[i.replace(' ','') for i in x])

0           [JamesCameron]
1          [GoreVerbinski]
2              [SamMendes]
3       [ChristopherNolan]
4          [AndrewStanton]
               ...
4804     [RobertRodriguez]
4805         [EdwardBurns]
4806          [ScottSmith]
4807          [DanielHsia]
4808     [BrianHerzlinger]
Name: crew, Length: 4806, dtype: object

In [140]:
# Now I am conctinating the columns

In [141]:
movies['tags']=movies['keywords']+movies['crew']+movies['cast']+movies['overview']+movies['genres']

In [142]:
# movies.head()

In [143]:
new_df=movies[['movie_id','title','tags']]

In [144]:
new_df

,movie_id,title,tags
0,19995,Avatar,"[culture clash, future, space war, space colon..."
1,285,Pirates of the Caribbean: At World's End,"[ocean, drug abuse, exotic island, east india ..."
2,206647,Spectre,"[spy, based on novel, secret agent, sequel, mi..."
3,49026,The Dark Knight Rises,"[dc comics, crime fighter, terrorist, secret i..."
4,49529,John Carter,"[based on novel, mars, medallion, space travel..."
...,...,...,...
4804,9367,El Mariachi,"[united states–mexico barrier, legs, arms, pap..."
4805,72766,Newlyweds,"[Edward Burns, Edward Burns, Kerry Bishé, Mars..."
4806,231617,"Signed, Sealed, Delivered","[date, love at first sight, narration, investi..."
4807,126186,Shanghai Calling,"[Daniel Hsia, Daniel Henney, Eliza Coupe, Bill..."
4808,25975,My Date with Drew,"[obsession, camcorder, crush, dream girl, Bria..."

In [145]:
# Now convert list into string

In [146]:
new_df['tags']=new_df['tags'].apply(lambda x:" ".join(x))

C:\Users\sawsu\AppData\Local\Temp\ipykernel_12856\487797088.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(lambda x:" ".join(x))

In [147]:
new_df

,movie_id,title,tags
0,19995,Avatar,culture clash future space war space colony so...
1,285,Pirates of the Caribbean: At World's End,ocean drug abuse exotic island east india trad...
2,206647,Spectre,spy based on novel secret agent sequel mi6 bri...
3,49026,The Dark Knight Rises,dc comics crime fighter terrorist secret ident...
4,49529,John Carter,based on novel mars medallion space travel pri...
...,...,...,...
4804,9367,El Mariachi,united states–mexico barrier legs arms paper k...
4805,72766,Newlyweds,Edward Burns Edward Burns Kerry Bishé Marsha D...
4806,231617,"Signed, Sealed, Delivered",date love at first sight narration investigati...
4807,126186,Shanghai Calling,Daniel Hsia Daniel Henney Eliza Coupe Bill Pax...
4808,25975,My Date with Drew,obsession camcorder crush dream girl Brian Her...

In [148]:
new_df['tags'][0]

'culture clash future space war space colony society space travel futuristic romance space alien tribe alien planet cgi marine soldier battle love affair anti war power relations mind and soul 3d James Cameron Sam Worthington Zoe Saldana Sigourney Weaver In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy Science Fiction'

In [149]:
new_df['tags']=new_df['tags'].apply(lambda x:x.lower())

C:\Users\sawsu\AppData\Local\Temp\ipykernel_12856\4224080999.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(lambda x:x.lower())

## Bag Of Words(BoW)
* Bag of Words (BoW) is a technique in Natural Language Processing (NLP). 
* It is widely used to transform textual data into machine-readable format.

In [150]:
# Now Its time for Text vecterization 
# We calculating similarity score between the movies

In [151]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=5000,stop_words='english')

In [152]:
# A sparse matrix is a matrix where the majority of elements are zero, 
# typically containing only a small fraction of non-zero values.

In [153]:
Text_vector=cv.fit_transform(new_df['tags']).toarray()

In [154]:
Text_vector

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [155]:
print(cv.get_feature_names_out())

['000' '007' '10' ... 'zooey' 'zucker' 'zwick']

In [156]:
import nltk
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [157]:
def stem(text):
    y=[]
    for i in text.split(): 
        y.append(ps.stem(i))
    return " ".join(y)

In [158]:
new_df['tags']=new_df['tags'].apply(stem)

C:\Users\sawsu\AppData\Local\Temp\ipykernel_12856\3514595201.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(stem)

In [159]:
ps.stem('loved','loving')

'love'

In [160]:
Text_vector

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [161]:
cv.get_feature_names_out()

array(['000', '007', '10', ..., 'zooey', 'zucker', 'zwick'], dtype=object)

In [180]:
from sklearn.metrics.pairwise import cosine_similarity
similarity=cosine_similarity(Text_vector)

In [187]:
similarity

array([[1.        , 0.06885304, 0.04948717, ..., 0.03142697, 0.05345225,
        0.        ],
       [0.06885304, 1.        , 0.04259177, ..., 0.04057204, 0.        ,
        0.        ],
       [0.04948717, 0.04259177, 1.        , ..., 0.01944039, 0.08817334,
        0.        ],
       ...,
       [0.03142697, 0.04057204, 0.01944039, ..., 1.        , 0.06299408,
        0.03276488],
       [0.05345225, 0.        , 0.08817334, ..., 0.06299408, 1.        ,
        0.03715188],
       [0.        , 0.        , 0.        , ..., 0.03276488, 0.03715188,
        1.        ]])

In [181]:
similarity[0]

array([1.        , 0.06885304, 0.04948717, ..., 0.03142697, 0.05345225,
       0.        ])

In [182]:
sorted(similarity[0])[-10:-1]

[np.float64(0.3618136134933163),
 np.float64(0.3703280399090205),
 np.float64(0.3829708431025352),
 np.float64(0.3841143835488626),
 np.float64(0.3920784235278427),
 np.float64(0.3962969619506085),
 np.float64(0.4278406467922595),
 np.float64(0.43622020338771716),
 np.float64(0.4839354795704658)]

In [166]:
# Index position is loose
# sorted(cs[0],reverse=True)

In [183]:
sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x:x[1])[1:6]

[(2405, np.float64(0.4839354795704658)),
 (1533, np.float64(0.43622020338771716)),
 (3160, np.float64(0.4278406467922595)),
 (838, np.float64(0.3962969619506085)),
 (4336, np.float64(0.3920784235278427))]

In [188]:
print(new_df[new_df['title']=='Avatar'].index[0])

0

In [184]:
# def recommended(movie):
#     movie_index=new_df[new_df['title']==movie].index[0]
#     distance=similarity[movie_index]
#     movie_list=sorted(list(enumerate(distance)),reverse=True,key=lambda x:x[1])[1:6]
#     for i in movie_list: 
#         print(i[0])

In [189]:
recommended('Avatar')

2405
1533
3160
838
4336

In [190]:
new_df.iloc[2405].title

'Aliens'

In [191]:
def recommended(movie):
    movie_index=new_df[new_df['title']==movie].index[0]
    distance=similarity[movie_index]
    movie_list=sorted(list(enumerate(distance)),reverse=True,key=lambda x:x[1])[1:6]
    
    for i in movie_list: 
        print(new_df.iloc[i[0]].title)

In [192]:
recommended('Avatar')

Aliens
Moonraker
Alien
Alien³
Silent Running

In [196]:
import pickle
pickle.dump(new_df,open('movies.pkl','wb'))
pickle.dump(new_df,open('movie_list.pkl','wb'))
pickle.dump(similarity,open('similarity.pkl','wb'))